In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,10)        ##it starts form intial no. but ends with one no. before

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(18)      ##its default initial value is 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
np.arange(1,46,5)      ##the third no. indicates the gap between two no.

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [ ]:
np.zeros(5)         ##initial dtype is float

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(4,int)

array([0, 0, 0, 0])

In [ ]:
np.zeros((4,5))       ##putting double bracket is compulsory otherwise it will take 5 as dtype and throw an error

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((2,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [2]:
import numpy as np

In [3]:
np.linspace(0,1,5)         ##it creates equally spaced elements where 5 is no. of elements

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.eye(3)                ##it creates an identity matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.random.rand(3,2)         ##it creates an matrix with random no. between 0 & 1

array([[0.79854307, 0.50481394],
       [0.23167041, 0.36906872],
       [0.57954378, 0.46614783]])

In [11]:
np.random.randn(3,2)       ##it creates an matrix with random no. including negative no.

array([[-0.31213937,  2.33302688],
       [ 0.00808969,  0.80687002],
       [ 1.81840261, -1.49269728]])

In [12]:
np.random.randint(1,5)       ##it randomly chooses an integer between the given range

3

In [13]:
np.random.randint(1,100,50)     ##it randomly chooses 50 integer between given range

array([37, 60, 97, 61, 14, 52, 23, 18, 28, 20, 58,  4, 36, 86,  3, 40, 45,
       57, 88, 51, 72, 37, 74, 99, 40, 16, 61,  6, 86, 49, 34, 18, 85, 72,
       53, 58, 82, 75, 77, 27, 83, 87, 51, 63, 53, 36, 23, 47, 27, 64])

In [20]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
rand_array=np.random.randint(0,100,20)             ##it creates an random array of 20 elements between 0-100
rand_array

array([25, 68, 54, 47, 64, 15, 42, 57, 95, 90, 37,  4, 56, 10,  1, 58, 55,
       49, 26, 30])

In [18]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [22]:
rand_array.min()     ##it gives the min. no. from the array

1

In [23]:
rand_array.max()      ##it gives the max. no. from the array

95

In [24]:
rand_array.argmin()    ##it gives the index of the min. value

14

In [26]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a.T        ##it gives the transpose of matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
a=np.random.rand(2,3)
a

array([[0.29150614, 0.13945598, 0.97078839],
       [0.49164637, 0.44059243, 0.49848773]])

In [30]:
a.T

array([[0.29150614, 0.49164637],
       [0.13945598, 0.44059243],
       [0.97078839, 0.49848773]])

In [32]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
sample_array[3:7]       ## slicing of an array wiht the help of index

array([13, 14, 15, 16])

In [34]:
sample_array[3:7]=100        ## mutatinge the array using slice
sample_array

array([ 10,  11,  12, 100, 100, 100, 100,  17,  18,  19,  20])

In [37]:
sample_array[:]=100      ## this mutates the whole array
sample_array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [38]:
## TWO DIMENSIONAL ARRAY

In [39]:
import numpy as np

In [40]:
sample_matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
sample_matrix[2,:]     ## (2) represents row and (:) represents column----->it means 2nd row and columns

array([7, 8, 9])

In [42]:
sample_matrix[2]         ## works same as above

array([7, 8, 9])

In [43]:
sample_matrix[0:2,2]

array([3, 6])

In [46]:
sample_matrix[:,(2,1)]

array([[3, 2],
       [6, 5],
       [9, 8]])

In [48]:
sample_array=np.arange(1,10)
sample_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
sample_array+sample_array     ##it adds the elements


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
np.exp(sample_array)    ## it takes exponential of all elements

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [53]:
np.sqrt(sample_array)     ##it takes square root of all elements

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [55]:
np.log(sample_array)    ## it takes logrithm of all elements

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [57]:
np.max(sample_array)      ## it works same for min and thier index (argmin)

9

In [58]:
np.square(sample_array)    ## it takes square of all elements

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [59]:
np.std(sample_array)      ## it takes standard deviation

2.581988897471611

In [60]:
np.mean(sample_array)       ## it takes mean 

5.0

In [61]:
np.var(sample_array)      ## it takes variance

6.666666666666667

In [62]:
array=np.random.randn(3,4)
array

array([[ 0.12903524, -0.59836949, -0.89883288,  1.29135122],
       [-0.60082874, -0.97300615,  0.11293627,  1.3254184 ],
       [ 1.09700317,  0.44607519,  0.34800486,  1.34448973]])

In [63]:
np.round(array,decimals=3)     ## it rounds off the value upto decimal 3

array([[ 0.129, -0.598, -0.899,  1.291],
       [-0.601, -0.973,  0.113,  1.325],
       [ 1.097,  0.446,  0.348,  1.344]])

In [64]:
num=np.array([1,2,3,4,5,62,3,4,7,8,9])     ## it gives all the unique elements

np.unique(num)

array([ 1,  2,  3,  4,  5,  7,  8,  9, 62])